namespace ForgePC;

public sealed partial class MainViewModel
{
 private readonly GpuActivityProbe gpuProbe=new();private DateTimeOffset gpuAt;private bool gpuReading;private string gpuUsage="Not sampled",networkActivity="Warming up";private long? networkReceived,networkSent;private DateTimeOffset networkAt;
 internal async Task SampleGraphicsForValidationAsync(){GpuUsage=await Task.Run(gpuProbe.Read);await Task.Delay(1200);GpuUsage=await Task.Run(gpuProbe.Read);}
 public string GpuUsage{get=>gpuUsage;private set=>Set(ref gpuUsage,value);}
 public string NetworkActivity{get=>networkActivity;private set=>Set(ref networkActivity,value);}
 public string AppliedCount=>History.Where(j=>j.IsActive).Sum(j=>j.Operations.Count(op=>op.State=="applied"))+" verified at last apply";
 public string CurrentPowerPlan=>Operations.FirstOrDefault(o=>o.Id=="power")?.Current??"Not read";
 private async Task SampleExtendedAsync()
 {
  try{var statistics=await Task.Run(()=>System.Net.NetworkInformation.NetworkInterface.GetAllNetworkInterfaces().Where(n=>n.OperationalStatus==System.Net.NetworkInformation.OperationalStatus.Up&&n.NetworkInterfaceType!=System.Net.NetworkInformation.NetworkInterfaceType.Loopback).Select(n=>n.GetIPStatistics()).ToArray());long received=statistics.Sum(s=>s.BytesReceived),sent=statistics.Sum(s=>s.BytesSent);var now=DateTimeOffset.UtcNow;double seconds=(now-networkAt).TotalSeconds;if(networkReceived.HasValue&&seconds>.25&&received>=networkReceived&&sent>=networkSent)NetworkActivity=$"↓ {(received-networkReceived.Value)/seconds/1024:0.0} · ↑ {(sent-networkSent!.Value)/seconds/1024:0.0} KB/s";else NetworkActivity="Warming up / adapter changed";networkReceived=received;networkSent=sent;networkAt=now;}catch(Exception error){logger.Error(error);NetworkActivity="Unavailable";}
  if(gpuReading||(DateTimeOffset.UtcNow-gpuAt).TotalSeconds<30)return;gpuReading=true;gpuAt=DateTimeOffset.UtcNow;
  try{GpuUsage=await Task.Run(gpuProbe.Read);}catch(Exception error){logger.Error(error);GpuUsage="Unavailable";}finally{gpuReading=false;}
 }
 public string ProfileAssessment
 {
  get{if(!Profiles.Contains(Profile))return "Imported profile: inspect its exact queue and capability results.";var document=ResolveProfile(Profile);return string.Join("\n",document.Parameters.Select(p=>{var definition=Catalog.Get(p.Id);var item=Operations.Single(o=>o.Id==p.Id);var blocked=!item.Eligible||p.Id=="power"&&!Plans.Any(plan=>plan.Id==p.Value);return $"{definition.Title}: {(blocked?"Unsupported / unavailable":item.Current==Friendly(p.Id,p.Value)?"Already matches":"Proposed "+Friendly(p.Id,p.Value))} · {definition.Risk}"+(definition.Restart?" · restart may be required":"");}));}
 }
 public FeatureTools Tools {get;}
 public Command OptimizeMyPc {get;private set;}=null!;
 public Command RemoveStaged {get;private set;}=null!;
 public Command UndoSelected{get;private set;}=null!;public Command UndoCategory{get;private set;}=null!;public Command UndoAll{get;private set;}=null!;
 public Command UndoLatest {get;private set;}=null!;
 public Command ShowControls {get;private set;}=null!;
 private async Task RestoreSubset(Journal journal,IReadOnlySet<string> ids)
 {Busy=true;try{var issues=await Task.Run(()=>engine.RestoreSelectedAsync(journal,ids));Status=issues.Count==0?"Selected original values verified. Other session settings may remain active.":"Selected undo needs review: "+string.Join("; ",issues);await ReloadHistory();Invalidate();if(!recoveryOnly)await RefreshSettings();}finally{Busy=false;}}
 private DateTimeOffset lastGameCheck;
 [System.Runtime.InteropServices.DllImport("kernel32.dll",CharSet=System.Runtime.InteropServices.CharSet.Unicode,SetLastError=true)] [return:System.Runtime.InteropServices.MarshalAs(System.Runtime.InteropServices.UnmanagedType.Bool)] private static extern bool QueryFullProcessImageName(IntPtr process,uint flags,System.Text.StringBuilder path,ref uint size);
 private async Task DetectArmedGameAsync()
 {
  if(Busy||Tools.Busy||(Actions?.Busy??false)||gameJournal!=null||desired.Count>0||History.Any(j=>j.IsActive)||!SavedGames.Any(g=>g.Automatic)||(DateTimeOffset.UtcNow-lastGameCheck).TotalSeconds<10)return;lastGameCheck=DateTimeOffset.UtcNow;var armed=SavedGames.Where(g=>g.Automatic).ToArray();
  var found=await Task.Run(()=>{foreach(var process in System.Diagnostics.Process.GetProcesses()){using(process){try{var path=new System.Text.StringBuilder(32768);uint count=32768;if(!QueryFullProcessImageName(process.Handle,0,path,ref count))continue;var game=armed.FirstOrDefault(g=>System.IO.Path.GetFullPath(g.Executable).Equals(path.ToString(),StringComparison.OrdinalIgnoreCase));if(game!=null)return(game,entry:new ProcessEntry(process.Id,process.StartTime.ToUniversalTime().Ticks,process.ProcessName,process.WorkingSet64));}catch(Exception error){System.Diagnostics.Trace.TraceWarning("Game identity inspection: "+error.GetType().Name);}}}return(game:(SavedGame?)null,entry:(ProcessEntry?)null);});
  if(found.game==null||found.entry==null||Busy||Tools.Busy||desired.Count>0||History.Any(j=>j.IsActive))return;SelectedGame=found.entry;await RefreshSettings();await LoadProfile(ResolveProfile(found.game.Profile,safeOnly:true));await PreviewQueue();if(CanApply)await ApplyQueue(true);else{desired.Clear();PersistQueue();Status="Armed game profile already matches; no Windows changes required.";}
 }
 private ProcessPriorityManager? priorities;public string[] PriorityChoices{get;}=ProcessPriorityManager.Targets;private string priority="Normal";public string Priority{get=>priority;set{if(PriorityChoices.Contains(value))Set(ref priority,value);}}
 public Command ApplyPriority{get;private set;}=null!;public Command RestorePriorities{get;private set;}=null!;
 private async Task RestorePrioritySessions(){if(priorities!=null)await Task.Run(priorities.RestoreAll);}
 public System.Collections.ObjectModel.ObservableCollection<SavedGame> SavedGames{get;}=[];
 private SavedGame? savedGame;public SavedGame? SelectedSavedGame{get=>savedGame;set=>Set(ref savedGame,value);}
 public Command AddGame{get;private set;}=null!;public Command StageGame{get;private set;}=null!;public Command LaunchGame{get;private set;}=null!;public Command RemoveGame{get;private set;}=null!;public Command ArmGame{get;private set;}=null!;public Command DisarmGame{get;private set;}=null!;
 private void InitializeExpandedCommands(Func<Func<object?,Task>,Func<bool>?,Command> make,string dataRoot)
 {
  priorities=new(System.IO.Path.Combine(dataRoot,"priority-recovery"));
  ApplyPriority=make(async _=>{if(SelectedGame==null){Status="Select a running process in Profiles.";return;}if(!ui.Confirm("Set the selected process to "+Priority+"? Higher priority can reduce responsiveness of other apps. It does not guarantee faster games. The original priority is saved and checked before restore.","Review process priority"))return;Busy=true;try{await Task.Run(()=>priorities.Apply(SelectedGame,Priority));Status="Process priority read-back verified. Use Restore priorities or close EZoptimizer normally to attempt exact undo.";}finally{Busy=false;}},()=>!Busy&&!Tools.Busy&&!(Actions?.Busy??false));
  RestorePriorities=make(async _=>{Busy=true;try{await RestorePrioritySessions();Status="Priority recovery verified or original processes ended.";}finally{Busy=false;}},()=>!Busy&&!Tools.Busy&&!(Actions?.Busy??false));
  var library=new GameLibrary(System.IO.Path.Combine(dataRoot,"games.json"));try{foreach(var game in library.Load())SavedGames.Add(game);}catch(Exception error){Error(error);}
  AddGame=make(_=>{var executable=ui.ChooseGame();if(executable==null)return Task.CompletedTask;var game=new SavedGame(Guid.NewGuid().ToString("N"),System.IO.Path.GetFileNameWithoutExtension(executable),executable,Profiles.Contains(Profile)?Profile:"Gaming");SavedGames.Add(game);try{library.Save(SavedGames);}catch{SavedGames.Remove(game);throw;}SelectedSavedGame=game;Status="Game saved with its selected profile. Stage and preview before applying; launching alone changes no Windows settings.";return Task.CompletedTask;},()=>!Busy&&!Tools.Busy&&!(Actions?.Busy??false));
  StageGame=make(async _=>{if(SelectedSavedGame==null){Status="Select a saved game.";return;}await LoadProfile(ResolveProfile(SelectedSavedGame.Profile));await PreviewQueue();Page="Profiles";},()=>!Busy&&!Tools.Busy&&!(Actions?.Busy??false));
  LaunchGame=make(_=>{if(SelectedSavedGame==null){Status="Select a saved game.";return Task.CompletedTask;}var game=SelectedSavedGame;if(!System.IO.File.Exists(game.Executable))throw new InvalidOperationException("The game executable is missing. Update the library entry.");if(!ui.Confirm("Launch this executable? Only launch games you trust. This launches the game; apply its reviewed profile separately.\n\n"+game.Executable,"Launch "+game.Name))return Task.CompletedTask;System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo(game.Executable){UseShellExecute=true,WorkingDirectory=System.IO.Path.GetDirectoryName(game.Executable)});Status="Game launch requested. Refresh running apps, then select its process for a reviewed game session.";return Task.CompletedTask;},()=>!Busy&&!Tools.Busy&&!(Actions?.Busy??false));
  ArmGame=make(async _=>{if(SelectedSavedGame==null){Status="Select a saved game.";return;}var game=SelectedSavedGame;await RefreshSettings();await LoadProfile(ResolveProfile(game.Profile,safeOnly:true));await PreviewQueue();if(!ui.Confirm("Automatically apply only safe supported recommendations from this saved profile when this exact game executable is detected? The app must remain open. Each launch captures fresh originals, checks availability and verifies writes. Existing active sessions or a nonempty review queue block automation. Exact undo is attempted when the selected process or app closes.\n\n"+game.Name+" · "+game.Profile+"\n"+string.Join("\n",Review.Select(row=>row.Title+": "+row.Before+" → "+row.After)),"Arm reviewed game profile"))return;var armed=game with{Automatic=true};var index=SavedGames.IndexOf(game);SavedGames[index]=armed;try{library.Save(SavedGames);}catch{SavedGames[index]=game;throw;}SelectedSavedGame=armed;desired.Clear();PersistQueue();Status="Reviewed game profile armed. Keep EZoptimizer open; any staged queue or active session blocks automatic application.";},()=>!Busy&&!Tools.Busy&&!(Actions?.Busy??false));
  DisarmGame=make(_=>{if(SelectedSavedGame==null){Status="Select a saved game.";return Task.CompletedTask;}var game=SelectedSavedGame;var disarmed=game with{Automatic=false};var index=SavedGames.IndexOf(game);SavedGames[index]=disarmed;try{library.Save(SavedGames);}catch{SavedGames[index]=game;throw;}SelectedSavedGame=disarmed;Status="Automatic activation disabled. An already active session still needs its normal recovery.";return Task.CompletedTask;},()=>!Busy&&!Tools.Busy&&!(Actions?.Busy??false));
  RemoveGame=make(_=>{if(SelectedSavedGame==null){Status="Select a saved game.";return Task.CompletedTask;}var game=SelectedSavedGame;SavedGames.Remove(game);try{library.Save(SavedGames);}catch{SavedGames.Add(game);throw;}SelectedSavedGame=null;Status="Library entry removed. Game files were not changed.";return Task.CompletedTask;},()=>!Busy&&!Tools.Busy&&!(Actions?.Busy??false));
  RemoveStaged=make(p=>{if(p is string id){desired.Remove(id);PersistQueue();}return Task.CompletedTask;},()=>!Busy);
  UndoLatest=make(async _=>{var active=History.FirstOrDefault(j=>j.IsActive);if(active!=null)await Restore(active);else Status="No active changes need undo.";},()=>!Busy);
  UndoSelected=make(async p=>{if(p is OperationRecord op){var journal=History.FirstOrDefault(j=>j.IsActive&&j.Operations.Contains(op));if(journal==null){Status="This operation is already restored.";return;}await RestoreSubset(journal,new HashSet<string>{op.Id});}},()=>!Busy&&!Tools.Busy&&!(Actions?.Busy??false));
  UndoCategory=make(async _=>{var journal=History.FirstOrDefault(j=>j.IsActive);if(journal==null){Status="No active session.";return;}var ids=journal.Operations.Where(op=>Category=="All"||Catalog.Get(op.Id).Category==Category).Select(op=>op.Id).ToHashSet();if(ids.Count==0){Status="No active operations in this category.";return;}await RestoreSubset(journal,ids);},()=>!Busy&&!Tools.Busy&&!(Actions?.Busy??false));
  UndoAll=make(async _=>{if(!ui.Confirm("Restore all recorded Windows preferences and saved startup registrations? External changes will be preserved. This does not reverse permanent cleanup or Windows repairs.","Restore all EZoptimizer changes"))return;foreach(var journal in History.Where(j=>j.IsActive).ToArray())await Restore(journal);Busy=true;try{var failures=new List<string>();try{await Tools.RestoreAllStartupAsync();}catch(Exception error){logger.Error(error);failures.Add("startup");}try{await RestorePrioritySessions();}catch(Exception error){logger.Error(error);failures.Add("process priority");}if(History.Any(j=>j.IsActive))failures.Add("Windows settings");Status=failures.Count==0?"All recorded originals verified or original processes ended.":"Recovery still needs review: "+string.Join(", ",failures)+". Other recovery groups were attempted.";}finally{Busy=false;}},()=>!Busy&&!Tools.Busy&&!(Actions?.Busy??false));
  ShowControls=make(p=>{Category=p is string category&&OptimizationAudit.Categories.Contains(category)?category:"All";Page="Optimize";return Task.CompletedTask;},()=>!Busy);
 }
}
