namespace ForgePC;

public record OptimizationContract(string Id,string Category,string Setting,string Method,string Windows10,string Windows11,string Benefit,string Disadvantages,string Administrator,string Restart,string Detect,string Apply,string Verify,string Restore,string Documentation)
{
 public string Summary=>$"Potential benefit: {Benefit}\nDisadvantages: {Disadvantages}\nWindows 10: {Windows10}\nWindows 11: {Windows11}\nMethod: {Method}\nAdministrator: {Administrator}\nRestart / sign-out: {Restart}\nDetect: {Detect}\nApply: {Apply}\nVerify: {Verify}\nRestore: {Restore}";
}
public static class OptimizationAudit
{
 public static readonly string[] Categories=["CPU","GPU","Memory","Gaming","Network","Storage","Startup","Services","Windows","Privacy","Power","Cleanup"];
 private const string Win10="Documented desktop API; app requires 22H2 (19045). Native writes not certified.";
 private const string Win11="Documented desktop API; capability checked. Native integration not certified.";
 public static OptimizationContract For(OperationDefinition d)
 {
  if(HardwareBackend.Contains(d.Id))return new(d.Id,d.Category,d.Title,HardwareBackend.Method(d.Id),"Windows 10 22H2; cmdlet, edition, device and policy checked at runtime.",d.Id=="hw:policy:dvr"?"Unsupported: Microsoft limits this policy to Windows 10.":"Windows 11; runtime capability checks. Native writes require Windows 11 validation.",d.Purpose,d.Tradeoff,"Administrator required.",d.Restart?"Restart / sign-out may be required; configured state is verified, not runtime performance.":"No forced restart; networking may briefly interrupt.","Fresh structured backend read; missing device/cmdlet/property is unavailable.","Compare exact saved expected state, invoke fixed backend, reread.","Independent backend read must exactly match the target; exit code alone is insufficient.","Durable original saved first. Restore only if current matches recorded target; exact original configuration, including absent policy and DHCP mode. External conflicts retained for review.",d.Documentation);
  string method,detect,apply,admin="No elevation for the current user's preference; Windows policy remains authoritative.",restart="No OS restart/sign-out; some apps may need reopening.";
  if(d.Id=="power") {method="SystemDirectory/powercfg.exe /getactivescheme, /list, /setactive GUID";detect="Parse active GUID and enumerate installed schemes; check scheme and active-scheme policy.";apply="Set only an installed scheme, after fresh expected-GUID comparison.";restart="None.";admin="Normally standard user; Windows policy/permissions can deny. No bypass.";}
  else if(ProcessorPower.Ids.Contains(d.Id)){var ac=d.Id.EndsWith("-ac")?"AC":"DC";method=$"PowrProf PowerGetActiveScheme / PowerRead{ac}ValueIndex / PowerWrite{ac}ValueIndex / PowerSetActiveScheme; subgroup 54533251-82be-4824-96c1-47b60b740d00; setting "+ProcessorPower.SettingId(d.Id);detect="Read scheme GUID and exact index; check AC/DC policy and active scheme.";apply=d.Id.Contains("-boost-")?"Validate documented boost index and scheme identity; write index and reactivate same scheme.":"Validate both boundaries and scheme identity, order paired changes, write index and reactivate same scheme.";restart="None; effective hardware behavior remains driver/firmware dependent.";admin="Normally standard user with power-setting access; denied policy/ACL blocks operation.";}
  else if(ServicePreferences.Contains(d.Id)){method="SCM OpenService(QUERY_CONFIG|CHANGE_CONFIG), QueryServiceConfigW, QueryServiceConfig2W(level 3), ChangeServiceConfigW(start type only)";detect="Read startup type and delayed-start flag for "+d.Id[8..]+"; missing/denied service is unavailable.";apply="Compare exact expected tuple; preserve delayed flag and all other configuration; set only startup type.";admin="Yes; per-action elevation. SCM can still deny.";restart="Saved configuration immediate; next service start/boot affects behavior. Running state untouched; no forced restart.";}
  else if(d.Id==PointerAcceleration.Id){method="SystemParametersInfoW GETMOUSE (0x0003) / SETMOUSE (0x0004), three-int array, flags 3";detect="Read both thresholds and acceleration level together.";apply="Keep captured thresholds, set reviewed level, persist and broadcast.";}
  else{var p=NativePreferences.Get(d.Id);method=$"SystemParametersInfoW GET 0x{p.Get:X4} / SET 0x{p.Set:X4}; {p.Parameter}; SPIF_UPDATEINIFILE|SPIF_SENDCHANGE (3)";detect="Read via matching SPI GET; validate "+(p.Numeric?$"integer {p.Minimum}..{p.Maximum}.":"Boolean/ANIMATIONINFO state.");apply="Compare captured value; call matching SPI SET with its operation-specific argument convention.";}
  return new(d.Id,d.Category,d.Title,method,Win10,Win11,Benefit(d),d.Tradeoff,admin,restart,detect,apply,"Repeat native read and compare exact typed target; API success alone is insufficient.","Persist original before mutation. If current equals target, write saved original through the same native method and read it back; already-original is a no-op, external changes are conflicts. CPU scheme identity/delayed-service flag must still match.",d.Documentation);
 }
 private static string Benefit(OperationDefinition d)=>d.Id switch
 {
  "power"=>"Can choose a workload-appropriate energy/responsiveness tradeoff. Benefit depends on the installed scheme, hardware and workload; no guaranteed FPS gain.",
  "cpu-boost-ac" or "cpu-boost-dc"=>"Choose a supported processor boost policy. Can trade throughput for heat, noise and energy; actual behavior depends on firmware and driver.",
  "cpu-min-ac" or "cpu-min-dc"=>"Can tune the processor's lower performance-state bound for energy or responsiveness tradeoffs. Higher minimums can waste energy; effect is hardware-dependent.",
  "cpu-max-ac" or "cpu-max-dc"=>"A lower upper bound may reduce heat/noise/power at the cost of throughput. Raising a previously restrictive bound may permit performance. No universal turbo-disabling or FPS claim.",
  "mouse-speed" or "mouse-acceleration"=>"Pointer comfort and predictable desktop movement; raw-input games may ignore it. No polling-rate or latency benefit claimed.",
  "keyboard-delay" or "keyboard-repeat"=>"Typing preference for held keys. No reduction in first-keypress latency.",
  "menu-delay"=>"Submenus can appear sooner or avoid accidental opening, according to preference. No game input-latency change.",
  "cursor-shadow"=>"Pointer visibility preference, with no established performance gain.",
  "menu-shadow"=>"Appearance preference for supported classic windows, with no established FPS gain.",
  "drag-contents"=>"Outline dragging can avoid repainting full contents on constrained systems; less visual feedback. No game performance claim.",
  _=>ServicePreferences.Contains(d.Id)?d.Purpose:"Reduced or restored desktop motion may improve comfort/perceived immediacy in apps that honor the preference. No game FPS improvement established."
 };
 public static IEnumerable<OptimizationContract> All=>Catalog.Operations.Select(For).Concat([
  new("startup-run","Startup","Current-user sign-in registration","Microsoft.Win32.Registry HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Run; unexpanded REG_SZ/REG_EXPAND_SZ; DeleteValue/SetValue/Flush",Win10,Win11,"Reduce unwanted sign-in launches.","The selected app may no longer launch at sign-in; other startup sources and Windows approval can override this registration.","No, for owned HKCU key; access failures surfaced.","Next sign-in; running app is untouched.","Enumerate names, exact data and registry type.","Flush durable original, compare current entry, remove only matching value.","Re-enumerate and require absence.","Restore exact original name/data/type only if absent or identical; verify through independent re-enumeration. External replacements preserved.","https://learn.microsoft.com/en-us/windows/win32/setupapi/run-and-runonce-registry-keys"),
  new("process-priority","Gaming","Selected running process priority","System.Diagnostics.Process.PriorityClass -> GetPriorityClass/SetPriorityClass; process handle with PID/start time",Win10,Win11,"May redistribute CPU time under contention; workload-dependent.","Higher priority can hurt other apps/audio/responsiveness; no guaranteed FPS gain. Realtime targets excluded.","Same-user accessible process normally no; protected/elevated processes can deny. No privilege bypass.","None; process lifetime only.","Read priority and verify PID plus creation time.","Durably capture original; recheck identity and expected class; set BelowNormal/Normal/AboveNormal.","Read back same process identity and compare target.","Restore saved class only for original PID/start identity and owned target. Ended identities are marked ended; external values preserved.","https://learn.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-setpriorityclass")
 ]);
}
